# Generated by Django 5.1.7 on 2026-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True, unique=True)),
                ('laptop_score', models.FloatField(default=0)),
                ('mobile_score', models.FloatField(default=0)),
                ('budget_avg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preferred_brands', models.JSONField(default=list)),
                ('preferred_usecases', models.JSONField(default=list)),
                ('top_products', models.JSONField(default=list)),
                ('total_events', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='BehaviourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('product_id', models.IntegerField()),
                ('product_type', models.CharField(max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('view_product', 'Xem sản phẩm'), ('search', 'Tìm kiếm'), ('add_to_cart', 'Thêm vào giỏ'), ('remove_from_cart', 'Xóa khỏi giỏ'), ('checkout', 'Thanh toán')], max_length=30)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'product_type'], name='api_behavio_custome_d90e73_idx')],
            },
        ),
    ]
