# Generated by Django 6.0.6 on 2026-06-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="book_id",
            new_name="product_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="clothing_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="electronic_id",
        ),
    ]
